### ISSUE TITLE
大哥在网站上放个客服的联系方式啊

### ISSUE THREAD

**Issue by taany6210** [netease-kit/NEMeeting#125]
老板让我问问有没有联系方式，老板说要接这个网易会议呢，找了半天也没找到联系方式。

**Comment by chandarlee** [comment]
请登录到 https://netease.im/ 网站在线咨询我们的商务和客服

**Comment by chandarlee** [comment]
> 老板让我问问有没有联系方式，老板说要接这个网易会议呢，找了半天也没找到联系方式。

请登录到 https://netease.im/ 网站在线咨询我们的商务和客服
