### ISSUE TITLE
会议组件和音视频g2冲突？

### ISSUE THREAD

**Issue by lichao315** [netease-kit/NEMeeting#82]
我的项目里用了G2组件来实现音视频业务，后又集成了网易会议的lib，当我在MainActivity里初始化了g2组件后，首次安装app，开启音视频会议后，发现摄像头打不开。如果我不初始化g2组件，开启音视频会议，摄像头就能正常打开，而此时如果进行1v1音视频通话时，由于没有初始化g2组件，而导致应用崩溃。

**Comment by liuqijun** [comment]
音视频的初始化同时只能有一个，在需要使用的时候进行初始化
